Bem-exercise
clever-cr/bem__exercise2 pull request #1
Opened 2022-10-05 18:56 UTC by clever-cr

2022-10-06 08:52 UTC, ritha-kankindi commented on index.html
> +          <img src="img/fb.png" />
Add class name to these image tags

2022-10-06 08:55 UTC, rithaven commented on index.html
> +              <img src="img/fb.png" />
Add a class name to these image tags

2022-10-06 09:09 UTC, ritha-kankindi approved these changes

2022-10-06 09:21 UTC, sezeranoJchrisostome requested changes
Well done @clever-cr, I left some comments for you,

2022-10-06 09:21 UTC, sezeranoJchrisostome commented on style.css
> +.navbar__menu-item {
You can group navbar styles together 
`block` `block__element` `block--modifier` or `block__element--modifier`

2022-10-06 09:21 UTC, sezeranoJchrisostome commented on style.css
> +.content__title {
You should start with block here

2022-10-06 09:21 UTC, sezeranoJchrisostome commented on style.css
> +
try to avoid unnecessary spaces like this

2022-10-06 09:21 UTC, sezeranoJchrisostome commented on style.css
> +.section__title {
Also here start with the block

2022-10-06 09:21 UTC, sezeranoJchrisostome commented on style.css
> +.section-card {
same here move this up so that its element would go underneath

2022-10-06 09:21 UTC, sezeranoJchrisostome commented on style.css
> +.general-section {
same here

2022-10-06 09:21 UTC, sezeranoJchrisostome commented on style.css
> +.general-section__cards--big-size{
this modifier should be up with general section not in the middle of the style of the other block

2022-10-06 09:21 UTC, sezeranoJchrisostome commented on style.css
> +  /* height: 821px; */
You can remove this

2022-10-06 14:38 UTC, sezeranoJchrisostome requested changes
well done @clever-cr, I left some miner things to change check them out

2022-10-06 14:38 UTC, sezeranoJchrisostome commented on index.html
> +          <a class="navbar__menu-item" href="#">Home</a>
You can improve your naming here `navbar__menu-items` `navbar__menu-item`

2022-10-06 14:38 UTC, sezeranoJchrisostome commented on index.html
> +              the quick fox jumps over the lazy dog the quick fox jumps over the
This element is out of its block

2022-10-06 14:38 UTC, sezeranoJchrisostome commented on index.html
> +            <p class="section__description section__description--card">
this block element also is out of its block

2022-10-06 14:38 UTC, sezeranoJchrisostome commented on index.html
> +            <p class="section__description section__description--card">
same here

2022-10-06 14:38 UTC, sezeranoJchrisostome commented on index.html
> +            <p class="section__description section__description--card">
same here

2022-10-06 14:38 UTC, sezeranoJchrisostome commented on index.html
> +            <p class="section__description section__description--card">
same here too

2022-10-06 14:38 UTC, sezeranoJchrisostome commented on index.html
> +            <p class="section__description section__description--card">
same here too

2022-10-07 07:46 UTC, ritha-kankindi approved these changes

2022-10-07 10:41 UTC, sezeranoJchrisostome reviewed
Well done @clever-cr 
LGMT 👌🏽

2022-10-07 11:06 UTC, sezeranoJchrisostome approved these changes

2022-10-07 12:57 UTC, Morrism1 requested changes
Some few things to change before approving.

2022-10-07 12:57 UTC, Morrism1 commented on index.html
> +    <div class="footer__copyright">
`footer__copyright` is positioned outside the Block `footer`

2022-10-07 12:57 UTC, Morrism1 commented on index.html
> +      <h6 class="footer__copyright-text">
This one too! is outside.

2022-10-07 12:57 UTC, Morrism1 commented on index.html
> +        <div>
DIV elements with no class. These are unnecessary. If you need them give them a className.

2022-10-07 12:57 UTC, Morrism1 commented on index.html
> +        <div>
This one too!

2026-06-13 13:00 UTC, closed without merging